# Generated by Django 4.0.5 on 2022-06-02 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unloading_date', models.DateField()),
                ('weight', models.FloatField()),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZMK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTCObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_weight', models.FloatField()),
                ('rtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZMK.rtc')),
            ],
        ),
        migrations.AddField(
            model_name='rtc',
            name='zmk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZMK.zmk'),
        ),
        migrations.AlterUniqueTogether(
            name='rtc',
            unique_together={('zmk', 'date', 'unloading_date', 'weight')},
        ),
    ]
