# Generated by Django 4.0.5 on 2022-06-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZMK', '0002_alter_zmk_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtc',
            name='upd',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rtcobject',
            name='rtc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='ZMK.rtc'),
        ),
    ]
