# Generated by Django 4.0.5 on 2022-06-02 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ZMK', '0003_rtc_upd_alter_rtcobject_rtc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtc',
            name='upd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rtcobject',
            name='rtc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ZMK.rtc'),
        ),
    ]
